COMMITTED_BATCH_STATUS = "committed"

PENDING_REVIEW_STATUS = "pending"
CONFIRMED_REVIEW_STATUS = "confirmed"
APPROVED_REVIEW_STATUS = "approved"
ACCEPTED_REVIEW_STATUS = "accepted"
IGNORED_REVIEW_STATUS = "ignored"
REJECTED_REVIEW_STATUS = "rejected"
DUPLICATE_REVIEW_STATUS = "duplicate"
INVALID_REVIEW_STATUS = "invalid"
COMMITTED_REVIEW_STATUS = "committed"

COMMIT_ELIGIBLE_REVIEW_STATUSES = frozenset(
    {
        CONFIRMED_REVIEW_STATUS,
        APPROVED_REVIEW_STATUS,
        ACCEPTED_REVIEW_STATUS,
    }
)

FINAL_REVIEW_STATUSES = frozenset(
    {
        COMMITTED_REVIEW_STATUS,
        IGNORED_REVIEW_STATUS,
        REJECTED_REVIEW_STATUS,
        DUPLICATE_REVIEW_STATUS,
        INVALID_REVIEW_STATUS,
    }
)

REPROCESSABLE_UNCONFIRMED_REVIEW_STATUSES = frozenset(
    {
        PENDING_REVIEW_STATUS,
    }
)

VISIBLE_REVIEW_STATUSES = frozenset(
    {
        PENDING_REVIEW_STATUS,
        *COMMIT_ELIGIBLE_REVIEW_STATUSES,
        *FINAL_REVIEW_STATUSES,
    }
)

COMMITTED_BATCH_READONLY_MESSAGE = "该批次已入账，如需重新处理，请先删除批次并确认回滚已入账交易。"
